	const_def
	const NO_ABILITY   ; 00
	const OVERGROW     ; 01
	const CHLOROPHYLL  ; 02
	const BLAZE        ; 03
	const SOLAR_POWER  ; 04
	const TORRENT      ; 05
	const RAIN_DISH    ; 06
	const SIMPLE       ; 07
	const UNAWARE      ; 08
	const MOODY        ; 09
	const SHED_SKIN    ; 0A
	const RUN_AWAY     ; 0B
	const SHIELD_DUST  ; 0C
	const SWARM        ; 0D
	const SNIPER       ; 0E
	const KEEN_EYE     ; 0F
	const TANGLED_FEET ; 10
	const BIG_PECKS    ; 11
	const TECHNICIAN   ; 12
	const HONEY_GATHER ; 13
	const HUSTLE       ; 14
	const PRESSURE     ; 15
	const UNNERVE      ; 16
	const PICKUP       ; 17
	const VOLT_ABSORB  ; 18
	const INTIMIDATE   ; 19
	const STATIC       ; 1A
	const LIGHTNINGROD ; 1B
	const SWIFT_SWIM   ; 1C
	const WATER_VEIL   ; 1D
	const POISON_POINT ; 1E
	const RIVALRY      ; 1F
	const SHEER_FORCE  ; 20
	const LEVITATE     ; 21
	const INSOMNIA     ; 22
	const SUPER_LUCK   ; 23
	const MOXIE        ; 24
	const NATURAL_CURE ; 25
	const SERENE_GRACE ; 26
	const SAND_VEIL    ; 27
	const ROUGH_SKIN   ; 28
	const INNER_FOCUS  ; 29
	const INFILTRATOR  ; 2A
	const STENCH       ; 2B
	const EFFECT_SPORE ; 2C
	const DRY_SKIN     ; 2D
	const DAMP         ; 2E
	const THICK_FAT    ; 2F
	const GLUTTONY     ; 30
	const ANTICIPATION ; 31
	const POISON_TOUCH ; 32
	const LIMBER       ; 33
	const CLOUD_NINE   ; 34
	const VITAL_SPIRIT ; 35
	const ANGER_POINT  ; 36
	const DEFIANT      ; 37
	const PICKPOCKET   ; 38
	const MAGNET_PULL  ; 39
	const STURDY       ; 3A
	const ANALYTIC     ; 3B
	const WATER_ABSORB ; 3C
	const LEAF_GUARD   ; 3D
	const REGENERATOR  ; 3E
	const MOTOR_DRIVE  ; 3F
	const FLAME_BODY   ; 40
	const SNOW_CLOAK   ; 41
	const ICE_BODY     ; 42
	const CUTE_CHARM   ; 43
	const PIXILIATE    ; 44
	const ADAPTABILITY ; 45
	const DOWNLOAD     ; 46
	const SAND_RUSH    ; 47
	const SCRAPPY      ; 48
	const ROCK_HEAD    ; 49
	const HYDRATION    ; 4A
	const GUTS         ; 4B
	const MOLD_BREAKER ; 4C
	const EARLY_BIRD   ; 4D
	const PRANKSTER    ; 4E
	const OWN_TEMPO    ; 4F
	const CURSED_BODY  ; 50
	const COMPOUNDEYES ; 51
	const HYPER_CUTTER ; 52
	const SHELL_ARMOR  ; 53
	const SOUNDPROOF   ; 54
	const AFTERMATH    ; 55
	const HARVEST      ; 56
	const BATTLE_ARMOR ; 57
	const FLASH_FIRE   ; 58
	const SHADOW_TAG   ; 59
	const RECKLESS     ; 5A
	const SAP_SIPPER   ; 5B
	const OVERCOAT     ; 5C
	const WEAK_ARMOR   ; 5D
	const HEALER       ; 5E
	const WHITE_SMOKE  ; 5F
	const TRUANT       ; 60
	const ILLUMINATE   ; 61
	const STEADFAST    ; 62
	const RATTLED      ; 63
	const IMPOSTER     ; 64
	const QUICK_FEET   ; 65
	const SYNCHRONIZE  ; 66
	const MAGIC_BOUNCE ; 67
	const TOUGH_CLAWS  ; 68
	const IMMUNITY     ; 69
	const MARVEL_SCALE ; 6A
	const MULTISCALE   ; 6B
	const IRON_FIST    ; 6C
	const MEGALAUNCHER ; 6D
	const UNBURDEN     ; 6E
	const BATTERY      ; 6F
	const NO_GUARD     ; 70
	const WATER_BUBBLE ; 71
	const DISGUISE     ; 72
	const HUGE_POWER   ; 73
	const STEELWORKER  ; 74
	const DRIZZLE      ; 75
	const MIRROR_ARMOR ; 76
	const STRONG_JAW   ; 77
	const ICE_FACE     ; 78
	const FRISK        ; 79
	const SHARPNESS    ; 7A
	const BULLETPROOF  ; 7B
	const MINDS_EYE    ; 7C
	const EARTH_EATER  ; 7D
	const LIGHT_METAL  ; 7E
	const CONTRARY     ; 7F
	const GOOD_AS_GOLD ; 80
	const SUCTION_CUPS ; 81
	const CUD_CHEW     ; 82
	const ARMOR_TAIL   ; 83
	const SAND_STREAM  ; 84
	const SPEED_BOOST  ; 85
	const WIND_RIDER   ; 86
	const TRACE        ; 87
	const JUSTIFIED    ; 88
	const POISON_HEAL  ; 89
	const NORMALIZE    ; 8A
	const WONDER_SKIN  ; 8B
	const STALL        ; 8C
	const HEAVY_METAL  ; 8D
	const LIQUID_OOZE  ; 8E
	const STICKY_HOLD  ; 8F
	const OBLIVIOUS    ; 90
	const SOLID_ROCK   ; 91
	const MAGMA_ARMOR  ; 92
	const ARENA_TRAP   ; 93
	const TOXIC_BOOST  ; 94
	const STORM_DRAIN  ; 95
	const COMPETITIVE  ; 96
	const FORECAST     ; 97
	const COLOR_CHANGE ; 98
	const PROTEAN      ; 99
	const REFRIGERATE  ; 9A
	const CLEAR_BODY   ; 9B
	const DROUGHT      ; 9C
	const AIR_LOCK     ; 9D
