	const_def
	const BERRYPLOT_ROUTEN02_1
	const BERRYPLOT_ROUTEN02_2
	const BERRYPLOT_ROUTEN02_3
	const BERRYPLOT_ROUTEN02_4
DEF NUM_BERRY_PLOTS EQU const_value

	const_def
	const BERRYGROWTH_PLANTED
	const BERRYGROWTH_STAGE1
	const BERRYGROWTH_STAGE2
	const BERRYGROWTH_STAGE3
	const BERRYGROWTH_FULLY_GROWN

	const_def $00, $40
	const MULCH_NONE
	const MULCH_QUICK
	const MULCH_FERTILE
	const MULCH_SPONGY

rsreset
DEF BERRYTREE_PLANTED_BERRY    rw
DEF BERRYTREE_LAST_GROWTH_DAY  rb
DEF BERRYTREE_LAST_GROWTH_HOUR rb
DEF BERRYTREE_MULCH            rb
rsset BERRYTREE_MULCH
DEF BERRYTREE_WATER            rb
DEF BERRYTREE_VISITED          rb
rsset BERRYTREE_VISITED
DEF BERRYTREE_NUM_PRODUCED     rb
rsset BERRYTREE_VISITED
DEF BERRYTREE_GROWTH_STAGE     rb
DEF BERRYTREE_TIME_TO_GROW     rb

DEF BERRYTREE_STRUCT_LEN EQU _RS

DEF BERRYTREE_WATER_MASK        EQU %00_111111
DEF BERRYTREE_MULCH_MASK        EQU %11_000000
DEF BERRYTREE_GROWTH_STAGE_MASK EQU %0000_0_111
DEF BERRYTREE_VISITED_F         EQU 3
DEF BERRYTREE_NUM_PRODUCED_MASK EQU %1111_0_000

DEF BERRY_MAXWATER_NORMAL EQU 8
DEF BERRY_MAXWATER_SPONGY EQU 16
