BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw PlaceholderBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw PlaceholderBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw PlaceholderBitmasks
	dw ScytherBitmasks
	dw PlaceholderBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PlaceholderBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw PlaceholderBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw PlaceholderBitmasks
	dw PolitoedBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw PlaceholderBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw PlaceholderBitmasks
	dw GirafarigBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw DunsparceBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw PlaceholderBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw SmoochumBitmasks
	dw PlaceholderBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	dw PlaceholderBitmasks
	assert_table_length NUM_POKEMON
