FramesPointers:
	table_width 3, FramesPointers
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba ZubatFrames
	dba GolbatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasFrames
	dba ParasectFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba MeowthFrames
	dba PersianFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba PlaceholderFrames
	dba DoduoFrames
	dba DodrioFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba ChanseyFrames
	dba TangelaFrames
	dba PlaceholderFrames
	dba HorseaFrames
	dba SeadraFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba StaryuFrames
	dba StarmieFrames
	dba PlaceholderFrames
	dba ScytherFrames
	dba PlaceholderFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba PlaceholderFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba PlaceholderFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba PichuFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba NatuFrames
	dba XatuFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba BellossomFrames
	dba MarillFrames
	dba AzumarillFrames
	dba PlaceholderFrames
	dba PolitoedFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba WooperFrames
	dba QuagsireFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba MurkrowFrames
	dba PlaceholderFrames
	dba MisdreavusFrames
	dba UnownFrames
	dba PlaceholderFrames
	dba GirafarigFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba DunsparceFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba ScizorFrames
	dba ShuckleFrames
	dba PlaceholderFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba KingdraFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba Porygon2Frames
	dba StantlerFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba KokopelliFrames
	dba PlaceholderFrames
	dba ElekidFrames
	dba MagbyFrames
	dba MiltankFrames
	dba BlisseyFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	dba PlaceholderFrames
	assert_table_length NUM_POKEMON
