AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw PlaceholderAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw PlaceholderAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw PlaceholderAnimationIdle
	dw ScytherAnimationIdle
	dw PlaceholderAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PlaceholderAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw PlaceholderAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw PlaceholderAnimationIdle
	dw PolitoedAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw PlaceholderAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw PlaceholderAnimationIdle
	dw GirafarigAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw DunsparceAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw PlaceholderAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw KokopelliAnimationIdle
	dw PlaceholderAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	dw PlaceholderAnimationIdle
	assert_table_length NUM_POKEMON
